### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by yri066** [Coloryr/MinecraftSkinRender#1]
Vulkan fails to start because it cannot find the following files:
MinecraftSkinRender/MinecraftSkinRender.Vulkan/spv/SkinV.spv and
MinecraftSkinRender/MinecraftSkinRender.Vulkan/spv/SkinF.spv

**Comment by Coloryr** [comment]
you need vulkan sdk
and run https://github.com/Coloryr/MinecraftSkinRender/blob/master/MinecraftSkinRender.Vulkan/glsl/glslbuild.ps1 in root directory, if linux run `.sh`

**Comment by yri066** [comment]
Thank you
